language: python
dist: bionic

install: |
  pip install --upgrade cython scipy
  pip install --upgrade pot pytest keras tensorflow scikit-learn
  pip install .
  if [ $(python -c "import sys; print(sys.version_info[0])") -eq 2 ]; then
    pip install keras==2.2.5
  fi

script: 
  - pytest -v energyflow

stages:
  - test
  - deploy

jobs:
  include:
    - python: 2.7
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - stage: deploy
      python: 3.8
      install: pip3 install --upgrade twine
      script: |
        python3 setup.py sdist bdist_wheel
        if [ "$TWINE_REPOSITORY" = "testpypi" ]; then
          export TWINE_PASSWORD=$TWINE_PASSWORD_TESTPYPI
        fi
      after_success: |
        if [ ! -z $TRAVIS_TAG ] || [ "$TWINE_REPOSITORY" = "testpypi" ]; then
          python3 -m twine upload --skip-existing dist/*
        fi

env:
  global:
    TWINE_USERNAME=__token__
    TWINE_REPOSITORY=testpypi

branches:
  only:
    - master
